### ISSUE TITLE
Constraints standalone

### ISSUE THREAD

**Issue by der-lukas** [sebcglbailey/framer-DesignComponents#4]
Hey!

I really love the idea of this module - I've been working on something with a kind of similar goal (https://github.com/der-lukas/framer-Symbols)

I've experimented around with the Constraints.coffee (without DesignComponents), since I was interested in achieving dynamic layouts as for example a container where children get added and the container(s) grows automatically.

I think it would be a good idea to make Constraints a seperate module that can be used as standalone and make it an external dependency for DesignComponents, because just having the power of setting constraints via code and for example not having to update the height of every parent would be a great module on its own.

What do you think about that?

**Comment by blaineb** [comment]
+1 To this.  It's an awesome module and would be super helpful on its own!

**Comment by sebcglbailey** [comment]
Constraints is now a separate module. Sorry for the delay in getting back to you :)

Find it here: https://github.com/sebcglbailey/framer-constraints

I'll get round to changing the design components module to use this one instead (but the internal one here is built differently as of right now, so will need to refactor).
